services:
  - type: web
    name: website-famnit
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    runtime: static
    envVars:
      - key: NODE_ENV
        value: production
